name: Dilithium3
type: sign
checksumsmall: b9541847294ba0b1f721468d44890d155f3a62e3bf752ceea6e9f136902654d9
checksumbig: 31b34edde2d0b1151e2c662d94c773a48432fbb9e32f22f0b29e861f32a70bc8
claimed-nist-level: 3
implementations:
    - name: amd64/ref
      version: 0.1
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
    - name: amd64/avx2
      version: 0.1
      supported_platforms:
        - architecture: x86_64
          operating_systems:
              - Linux
              - Darwin
